### ISSUE TITLE
New option to set miniicon size globally.

### ISSUE THREAD

**Issue by Nobutarou** [fvwmorg/fvwm#55]
I prefer big icons on FvwmIconMan. But, I have to set miniicon for each apps. Here is my config for example,

```
Style mlterm MiniIcon scalable/apps/terminal.svg:32x32, EWMHMiniIconOverride
Style Firefox MiniIcon scalable/apps/firefox.svg:32x32, EWMHMiniIconOverride
Style Geeqie MiniIcon scalable/apps/photocollage.svg:32x32, EWMHMiniIconOverride
```
![myscreen1](https://user-images.githubusercontent.com/1369439/39673816-15283038-517e-11e8-974c-cf3dc8a6dd98.png)
(Keepassx is not set and then the icon is small.)

I hope a new option something like EWMHMiniIconSize and to be able to use like this,
```
Style * EWMHMiniIconSize 32x32
```

**Comment by ThomasAdam** [comment]
Have a look at the `IconSize` option first of all.  From a quick scan of the code, I don't think it applies to MiniIcons.   Very easy to do, if not.  I'll take a look later, but do please let me know.

Kindly,
Thomas

**Comment by ThomasAdam** [comment]
It's not as simple as this, because:

* `IconSize` shouldn't imply the same for MiniIcons -- there needs to be a separate option for this.
* EWMH will mean you need to look at the various options to check for when this option should be applied.

I also need to point out that this entire exercise is nothing more than academic, as it won't be applied to fvwm.

Thanks.

**Comment by Nobutarou** [comment]
It is far beyond my ability. I am not a software developer. Sorry I cannot do any further. I hope my request to custom bigger icon size on FvwmIconMan could be implemented in future release.
